use std::{collections::HashMap, fs, path::Path};

const KEY_L1: &str = "l1";
const KEY_R1: &str = "r1";
const KEY_STICK_L: &str = "stick_l";
const KEY_STICK_R: &str = "stick_r";
const KEY_MIC_BTN: &str = "mic_btn";

fn main() {
    let svg_path = "assets/controller.svg";
    println!("cargo:rerun-if-changed={svg_path}");

    let svg_content = fs::read_to_string(svg_path).expect("assets/controller.svg not found");
    let doc = roxmltree::Document::parse(&svg_content).expect("failed to parse SVG");

    let inkscape_ns = "http://www.inkscape.org/namespaces/inkscape";
    let mut shapes: HashMap<String, ShapeInfo> = HashMap::new();

    for node in doc.descendants() {
        if !node.is_element() {
            continue;
        }

        let id = node
            .attribute((inkscape_ns, "label"))
            .or_else(|| node.attribute("id"))
            .unwrap_or("");
        if id.is_empty() {
            continue;
        }

        let info = match node.tag_name().name() {
            "path" => node.attribute("d").and_then(path_shape_info),
            _ => None,
        };

        if let Some(info) = info {
            shapes.insert(id.to_string(), info);
        }
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("svg_coords.rs");
    let mut code = String::from("// Auto-generated by build.rs — do not edit.\n\n");

    let mut entries: Vec<_> = shapes.iter().collect();
    entries.sort_by_key(|(k, _)| k.as_str());

    for (id, info) in &entries {
        let n = id_to_const(id);
        let (cx, cy) = info.center;
        let (w, h) = info.size;
        push_const(&mut code, &n, cx, cy);
        push_const(&mut code, &format!("{n}_SIZE"), w, h);
    }

    let l1 = require_center(&shapes, KEY_L1);
    let r1 = require_center(&shapes, KEY_R1);
    let stick_l = require_center(&shapes, KEY_STICK_L);
    let stick_r = require_center(&shapes, KEY_STICK_R);
    let mic_btn = require_center(&shapes, KEY_MIC_BTN);

    let trigger_offset = l1.1 * 0.6;
    let l2 = (l1.0, (l1.1 - trigger_offset).max(0.0));
    let r2 = (r1.0, (r1.1 - trigger_offset).max(0.0));

    let ps_btn = (
        (stick_l.0 + stick_r.0) / 2.0,
        (stick_l.1 + stick_r.1 + mic_btn.1) / 3.0,
    );

    let derived: &[(&str, (f32, f32))] = &[("L2", l2), ("R2", r2), ("PS_BTN", ps_btn)];

    for (name, (x, y)) in derived {
        push_const(&mut code, name, *x, *y);
    }

    fs::write(&out_path, &code).expect("failed to write svg_coords.rs");
}

struct ShapeInfo {
    center: (f32, f32),
    size: (f32, f32),
}

fn require_center(shapes: &HashMap<String, ShapeInfo>, key: &str) -> (f32, f32) {
    shapes
        .get(key)
        .map(|s| s.center)
        .unwrap_or_else(|| panic!("required SVG element '{key}' not found"))
}

fn id_to_const(id: &str) -> String {
    id.to_uppercase().replace(['-', ' '], "_")
}

fn push_const(code: &mut String, name: &str, x: f32, y: f32) {
    code.push_str(&format!(
        "#[allow(dead_code)]\npub const SVG_{name}: (f32, f32) = ({x:.4}_f32, {y:.4}_f32);\n"
    ));
}

fn path_shape_info(d: &str) -> Option<ShapeInfo> {
    let tokens = tokenize(d);
    let segments = segments(&tokens);

    let mut bbox = Bbox::empty();
    let mut cx = 0f32;
    let mut cy = 0f32;
    let mut sx = 0f32;
    let mut sy = 0f32;

    for seg in &segments {
        let abs = seg.cmd.is_uppercase();
        let cmd = seg.cmd.to_ascii_lowercase();
        let a = &seg.args;

        match cmd {
            'm' => {
                let mut j = 0;
                while j + 2 <= a.len() {
                    if abs {
                        cx = a[j];
                        cy = a[j + 1];
                    } else {
                        cx += a[j];
                        cy += a[j + 1];
                    }
                    bbox.add(cx, cy);
                    if j == 0 {
                        sx = cx;
                        sy = cy;
                    }
                    j += 2;
                }
            }

            'l' => {
                let mut j = 0;
                while j + 2 <= a.len() {
                    if abs {
                        cx = a[j];
                        cy = a[j + 1];
                    } else {
                        cx += a[j];
                        cy += a[j + 1];
                    }
                    bbox.add(cx, cy);
                    j += 2;
                }
            }

            'h' => {
                for &x in a {
                    if abs {
                        cx = x;
                    } else {
                        cx += x;
                    }
                    bbox.add(cx, cy);
                }
            }

            'v' => {
                for &y in a {
                    if abs {
                        cy = y;
                    } else {
                        cy += y;
                    }
                    bbox.add(cx, cy);
                }
            }

            'c' => {
                let mut j = 0;
                while j + 6 <= a.len() {
                    if abs {
                        bbox.add(a[j], a[j + 1]);
                        bbox.add(a[j + 2], a[j + 3]);
                        cx = a[j + 4];
                        cy = a[j + 5];
                    } else {
                        bbox.add(cx + a[j], cy + a[j + 1]);
                        bbox.add(cx + a[j + 2], cy + a[j + 3]);
                        cx += a[j + 4];
                        cy += a[j + 5];
                    }
                    bbox.add(cx, cy);
                    j += 6;
                }
            }

            's' => {
                let mut j = 0;
                while j + 4 <= a.len() {
                    if abs {
                        bbox.add(a[j], a[j + 1]);
                        cx = a[j + 2];
                        cy = a[j + 3];
                    } else {
                        bbox.add(cx + a[j], cy + a[j + 1]);
                        cx += a[j + 2];
                        cy += a[j + 3];
                    }
                    bbox.add(cx, cy);
                    j += 4;
                }
            }

            'q' => {
                let mut j = 0;
                while j + 4 <= a.len() {
                    if abs {
                        bbox.add(a[j], a[j + 1]);
                        cx = a[j + 2];
                        cy = a[j + 3];
                    } else {
                        bbox.add(cx + a[j], cy + a[j + 1]);
                        cx += a[j + 2];
                        cy += a[j + 3];
                    }
                    bbox.add(cx, cy);
                    j += 4;
                }
            }

            't' => {
                let mut j = 0;
                while j + 2 <= a.len() {
                    if abs {
                        cx = a[j];
                        cy = a[j + 1];
                    } else {
                        cx += a[j];
                        cy += a[j + 1];
                    }
                    bbox.add(cx, cy);
                    j += 2;
                }
            }

            'a' => {
                let mut j = 0;
                while j + 7 <= a.len() {
                    if abs {
                        cx = a[j + 5];
                        cy = a[j + 6];
                    } else {
                        cx += a[j + 5];
                        cy += a[j + 6];
                    }
                    bbox.add(cx, cy);
                    j += 7;
                }
            }

            'z' => {
                cx = sx;
                cy = sy;
            }

            _ => {}
        }
    }

    if !bbox.is_valid() {
        return None;
    }

    Some(ShapeInfo {
        center: bbox.center(),
        size: bbox.size(),
    })
}

#[derive(Debug)]
enum Token {
    Cmd(char),
    Num(f32),
}

fn tokenize(d: &str) -> Vec<Token> {
    let mut tokens = Vec::new();
    let mut chars = d.chars().peekable();

    while let Some(&ch) = chars.peek() {
        match ch {
            'A'..='D' | 'F'..='Z' | 'a'..='d' | 'f'..='z' => {
                tokens.push(Token::Cmd(ch));
                chars.next();
            }
            '0'..='9' | '.' | '-' | '+' => {
                tokens.push(Token::Num(parse_num(&mut chars)));
            }
            _ => {
                chars.next();
            }
        }
    }
    tokens
}

fn parse_num(chars: &mut std::iter::Peekable<std::str::Chars<'_>>) -> f32 {
    let mut s = String::new();

    if chars.peek().is_some_and(|&c| c == '-' || c == '+') {
        s.push(chars.next().unwrap());
    }
    while chars.peek().is_some_and(|c| c.is_ascii_digit()) {
        s.push(chars.next().unwrap());
    }
    if chars.peek() == Some(&'.') {
        s.push(chars.next().unwrap());
        while chars.peek().is_some_and(|c| c.is_ascii_digit()) {
            s.push(chars.next().unwrap());
        }
    }
    if chars.peek().is_some_and(|&c| c == 'e' || c == 'E') {
        s.push(chars.next().unwrap());
        if chars.peek().is_some_and(|&c| c == '+' || c == '-') {
            s.push(chars.next().unwrap());
        }
        while chars.peek().is_some_and(|c| c.is_ascii_digit()) {
            s.push(chars.next().unwrap());
        }
    }

    s.parse().unwrap_or(0.0)
}

struct Segment {
    cmd: char,
    args: Vec<f32>,
}

fn segments(tokens: &[Token]) -> Vec<Segment> {
    let mut out = Vec::new();
    let mut i = 0;

    while i < tokens.len() {
        let Token::Cmd(cmd) = tokens[i] else {
            i += 1;
            continue;
        };
        i += 1;

        let mut args = Vec::new();
        while i < tokens.len() {
            if let Token::Num(n) = tokens[i] {
                args.push(n);
                i += 1;
            } else {
                break;
            }
        }
        out.push(Segment { cmd, args });
    }
    out
}

#[derive(Clone, Copy)]
struct Bbox {
    min_x: f32,
    max_x: f32,
    min_y: f32,
    max_y: f32,
}

impl Bbox {
    fn empty() -> Self {
        Self {
            min_x: f32::MAX,
            max_x: f32::MIN,
            min_y: f32::MAX,
            max_y: f32::MIN,
        }
    }

    fn add(&mut self, x: f32, y: f32) {
        self.min_x = self.min_x.min(x);
        self.max_x = self.max_x.max(x);
        self.min_y = self.min_y.min(y);
        self.max_y = self.max_y.max(y);
    }

    fn is_valid(self) -> bool {
        self.min_x <= self.max_x && self.min_y <= self.max_y
    }

    fn center(self) -> (f32, f32) {
        (
            (self.min_x + self.max_x) / 2.0,
            (self.min_y + self.max_y) / 2.0,
        )
    }

    fn size(self) -> (f32, f32) {
        (self.max_x - self.min_x, self.max_y - self.min_y)
    }
}
